---
title: "Washington Hiking"
author: "Sergio Aquino"
date: 2020-11-30
output: html_output
---

# Import libraries

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytext)
library(SnowballC)
library(tidytuesdayR)
library(patchwork)
library(scales)
library(extrafont)
library(RColorBrewer)
library(here)

#install.packages(c("tidyverse", "tidytext", "SnowballC", "ggraph", "igraph","wordcloud", "topicmodels", "textdata", "htmlwidgets"))

```

# Load weekly data

```{r Load}

tt <- tidytuesdayR::tt_load(2020, week = 48)

hike <- tt$hike_data

dim(hike)
names(hike)
View(hike)

```

# Explore change in landline and mobile subscriptions (per 100 people) from 1990 to 2017

```{r Readme, eval = interactive()}

characters <- data.frame(word = c('trail','hike'))

hike_desc <- hike %>% 
  unnest_tokens(word, description) %>%  
  anti_join(stop_words, by = "word") %>%
  anti_join(characters, by = 'word') %>% 
  mutate(word = wordStem(word)) %>%
  count(word, sort = TRUE)

# word clouds
library(wordcloud)
library(wordcloud2)

wordcloud(
  words = hike_desc$word,
  freq = hike_desc$n,
  min.freq = 1,
  max.words = 200,
  random.order = FALSE,
  #vfont=c("serif","plain"),
  #rot.per=0.35,
  colors = brewer.pal(8, "Dark2")
)


```

#

```{r }


    
```

# Final Plot

```{r Visualize}

p3 <- (p1 | p2)  +
   plot_annotation(title = 'Landline and Mobile Phones in Europe from 1990 to 2017',
                 subtitle = 'Similar mobile phone adoption rates, but different landline retention',
                 caption = "Sergio Aquino | Data: OurWorldInData.org | #TidyTuesday",
                  theme = theme(plot.title = element_text(size = 16, face="bold"),
                                plot.subtitle =element_text(size = 14)))&
                 
                              
  theme(text = element_text('Calibri Light')) +
  theme(plot.background=element_rect(fill="#ffffff")) #f2f2f2
p3

```

```{r}

# This will save your most recent plot
ggsave(filename = "HistoricalPhoneUsage.png", p3, scale=1, width=14, height=10,dpi=300)

```
