---
title: "Canadian Wind Turbines"
date: 2020-10-26
output: html_output
---

# TidyTuesday week # 44

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)

theme_set(theme_light())

tuesdata <- tidytuesdayR::tt_load(2020, week = 44)

wind.turbines <- tuesdata$`wind-turbine`

```


# Data Analysis

```{r Load}
dim(wind.turbines)
glimpse(wind.turbines)
View(wind.turbines)

```


# Manufacurers Market Share


```{r Readme, eval = interactive()}

wind.turbines$manufacturer %>% 
  fct_lump_prop(0.10)  %>% 
  count(manufacturer, sort = T)   

wind.turbines %>% 
  mutate(manufacturer = fct_lump_prop(manufacturer, 0.1)) %>%
  ggplot(aes(manufacturer)) +
  geom_bar()

wind.turbines %>%
  count(manufacturer = fct_lump_prop(manufacturer, 0.1)) %>%
  mutate(manufacturer = fct_reorder(manufacturer, n)) %>%
  ggplot(aes(n, manufacturer)) +
  geom_col()

```

# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
ggsave(
  filename = "My TidyTuesday Plot.png",
  device = "png")

```
